## Day 1

#### ONE-DIMENSIONAL ARRAY

In [2]:
import numpy as np

In [3]:
#Question 1
patient_age_array = np.array([25, 30, 40, 22, 35, 50, 29, 60, 41, 28])

#Find the average age of the patients
np.mean(patient_age_array)

36.0

In [4]:
#Question 2
cholestorol_level = np.array([210, 180, 230, 250, 300, 220, 200, 190])

#Identify the highest cholesterol level from the list
np.max(cholestorol_level)

300

In [5]:
#Question 3
bp_reading = np.array([120, 130, 140, 135, 125, 110, 145, 120, 130, 140, 150, 135])

#Find the standard deviation of blood pressure readings
np.std(bp_reading)

11.055415967851333

In [6]:
#Question 4
patient_temp = np.array([37.1, 36.5, 37.3, 36.8, 37.0, 38.0, 36.7, 37.2, 36.9, 37.5])

#Calculate the mean temperature for the patient
np.mean(patient_temp)

37.1

In [7]:
#Question 5
patient_weight = np.array([60, 72, 65, 58, 82, 75, 70, 68, 66, 80])

#Return the reversed order of weights
reverse_weight = patient_weight[::-1]
reverse_weight

array([80, 66, 68, 70, 75, 82, 58, 65, 72, 60])

#### TWO DIMENSIONAL ARRAY

In [9]:
# Question 6
patient_data = np.array([[25, 70, 120],
                        [30, 80, 130],
                        [40, 85, 140]])

#Access the blood pressure of the second patient (use index)
patient_data[1,-1]

130

In [58]:
#Question 10
blood_tests = np.array([[5.6, 7.1, 6.2, 5.8],
[5.3, 6.9, 7.0, 6.5],
[5.7, 6.5, 6.8, 6.0],
[5.4, 7.0, 6.5, 5.9]])


#The sum of values across each row (representing total test results for each patient)
sum_bloodtests = np.sum(blood_tests, axis = 1)
sum_bloodtests

array([24.7, 25.7, 25. , 24.8])

In [12]:
#Question 15
patient_sugar = np.array([[80, 85, 90],
[95, 92, 88],
[85, 83, 82],
[100, 105, 110],
[75, 78, 80]])


#Find the average blood sugar level for the 3rd patient across all visits
average_sugar = np.mean(patient_sugar)
average_sugar

88.53333333333333

In [59]:
#Question 21
BMI = np.array([
    [22.1, 23.5],
    [27.8, 28.0],
    [21.2, 20.9]
])
# Perform the element-wise multiplication of BMI and weight (use a weight array: [60, 70, 80])

Weight = np.array([60, 70, 80]).reshape(-1, 1)  # Reshape to column vector

# Element-wise multiplication
result = BMI * Weight
result

array([[60],
       [70],
       [80]])

In [15]:
#Question 25
temperature_data = np.array([
    [37.0, 36.5, 37.1, 36.9, 37.0],
    [36.8, 37.3, 37.0, 36.7, 37.2]
])
# Find the maximum temperature for each patient
max_temperature = np.max(temperature_data, axis=1)
print("Maximum temperature for each patient:", max_temperature)

Maximum temperature for each patient: [37.1 37.3]


## Day 2

#### SERIES

In [17]:
import pandas as pd

In [61]:
#Question 1
bp_readings = pd.Series([120, 130, 140, 135, 125])

#Find the maximum and minimum blood pressure values
min_bp = bp_readings.min()
max_bp = bp_readings.max()
print(f'maximum BP = {max_bp} \nminimum BP = {min_bp}')

maximum BP = 140 
minimum BP = 120


In [26]:
#Question 2
cholestorol_level_s= pd.Series([210, 180, 220, 250, 280, 230])

#Filter patients with cholesterol levels above 240
cholestorol_level_s[cholestorol_level_s > 240]

3    250
4    280
dtype: int64

In [27]:
#Question 3
patient_ages = pd.Series([35, 40, 25, 30, 45, 50, 55, 60, 65, 70])

#Calculate the median age of the patients
patient_ages.median()

47.5

In [29]:
#Question 4
weight = pd.Series([70, 80, 75, 65, 85])

#Add 5 kg to each patient’s weight
weight += 5
weight

0    75
1    85
2    80
3    70
4    90
dtype: int64

In [30]:
#Question 5
temp_patient = pd.Series([37.2, 36.8, 37.5, 38.0, 36.6, 37.1, 36.9, 37.3, 37.4, 37.0])

#Calculate the average temperature of all 10 patients
temp_patient.mean()

37.17999999999999

#### DATAFRAME

In [39]:
#Question 6
patient_data1 = {'Name': ['John', 'Jane', 'Tom', 'Alice'],
        'Age': [28, 34, 45, 52],
        'Blood Pressure': [120, 130, 140, 150],
        'Cholesterol': [200, 220, 240, 260]}

#Select all patients with cholesterol greater than 220
df = pd.DataFrame(patient_data)
df[df['Cholesterol']> 220]

Name  Age  Blood Pressure  Cholesterol
2    Tom   45             140          240
3  Alice   52             150          260

In [64]:
#Question 11
patient_info = {
    "Name": ["Alice", "Bob", "Charlie", "Diana"],
    "Age": [25, 30, 35, 40],
    "Height (cm)": [165, 170, 175, 160],
    "Weight (kg)": [60, 70, 80, 55],
    "Blood Pressure (mmHg)": ["120/80", "130/85", "140/90", "110/70"]
}
patient_info = pd.DataFrame(patient_info)

#Calculate BMI using the formula BMI = Weight / (Height^2) (assume height in meters and weight in kilograms)
patient_info['BMI'] = patient_info['Weight (kg)']/(patient_info['Height (cm)']**2)

patient_info

Name  Age  Height (cm)  Weight (kg) Blood Pressure (mmHg)       BMI
0    Alice   25          165           60                120/80  0.002204
1      Bob   30          170           70                130/85  0.002422
2  Charlie   35          175           80                140/90  0.002612
3    Diana   40          160           55                110/70  0.002148

In [48]:
#Question 12
blood_test_result = {'Test ID': [1, 2, 3, 4],
                     'Patient Name': ['John', 'Jane', 'Tom', 'Alice'],
                     'Result': [5.6, 6.1, 5.8, 6.3]}

#Filter patients with a test result greater than 6.0
x = pd.DataFrame(blood_test_result)
x[x['Result'] > 6]

Test ID Patient Name  Result
1        2         Jane     6.1
3        4        Alice     6.3

In [53]:
#Question 16
patient_body_metrics = {
    "Patient": ["Alice", "Bob", "Charlie", "Diana"],
    "Age": [25, 30, 35, 40],
    "Weight (kg)": [60, 70, 80, 55],
    "Height (cm)": [165, 170, 175, 160]
}
patient_df = pd.DataFrame(patient_body_metrics)

#Use df.mean() to find the mean of each column
average_age = patient_df["Age"].mean()
average_height = patient_df["Weight (kg)"].mean()
average_weight = patient_df["Height (cm)"].mean()


66.25

In [56]:
#Question 18
data = {'Patient Name': ['John', 'Jane', 'Tom', 'Alice'],
        'Treatment Type': ['Surgery', 'Consultation', 'Surgery', 'Consultation'],
        'Treatment Date': ['2022-01-01', '2022-02-01', '2022-03-01', '2022-04-01']}

patient_treatment = pd.DataFrame(data)

#Find all records where the treatment type is "Surgery"
patient_treatment[patient_treatment['Treatment Type'] == 'Surgery']

Patient Name Treatment Type Treatment Date
0         John        Surgery     2022-01-01
2          Tom        Surgery     2022-03-01